/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_virginia_cs_storagedesk_common_NativeFile */

#ifndef _Included_edu_virginia_cs_storagedesk_common_NativeFile
#define _Included_edu_virginia_cs_storagedesk_common_NativeFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_virginia_cs_storagedesk_common_NativeFile
 * Method:    write
 * Signature: (Ljava/lang/String;[BJ)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_virginia_cs_storagedesk_common_NativeFile_write
  (JNIEnv *, jobject, jstring, jbyteArray, jlong);

/*
 * Class:     edu_virginia_cs_storagedesk_common_NativeFile
 * Method:    read
 * Signature: (Ljava/lang/String;JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_virginia_cs_storagedesk_common_NativeFile_read
  (JNIEnv *, jobject, jstring, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
